[package]
name = "bevogst"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.11"
bitvec = "1.0.1"
console_error_panic_hook = "0.1.7"
rand = "0.8.5"
rand_xoshiro = "0.6.0"
serde = "1.0.183"
wyhash = "0.5.0"
